org: heejongahn
app: galpi
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: galpi-server
provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: ap-northeast-2
    iamRoleStatements:
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource: 'arn:aws:secretsmanager:ap-northeast-2:591434487062:secret:${env:STAGE}/*'

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-dotenv-plugin

functions:
    hello:
        handler: src/server.hello
        events:
            - http:
                  path: hello
                  method: get
    registerWithFirebase:
        handler: src/server.registerWithFirebase
        events:
            - http:
                  path: register/firebase
                  method: post

iamRoleStatements:
    - Effect: Allow
      Action:
          - ssm:GetParameter
      Resource: 'arn:aws:ssm:ap-northeast-2:heejognahn@gmail.com:parameter/*'
